In [17]:
#list
my_l = [2, 1, 5, 4, 3]
my_l2 = [12, 21, 35, 44, 53]

new_lst=[]
for i in my_l :
    new_lst.append(i*2)
print(new_lst)

[4, 2, 10, 8, 6]


In [22]:
import numpy as np

my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8]
ar=np.array(my_list)

print(ar)
print(type(ar))
print(my_list)
print(type(my_list))

[0 1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5, 6, 7, 8]
<class 'list'>


In [24]:
a1 = [1, 2, 3]
b1 = [4, 5, 6]
print(a1+b1)
aa = np.array(a1)
ba = np.array(b1)
print(aa+ba)

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [28]:
data = [0,1,2,3,4,5,6,7,8,9]
x = np.array(data)

print(data*2)
print(x*2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [29]:
a = np.array([1,2,3])
b = np.array([10,20,30])

print(a==2)
print(b>10)
print((a==2)&(b>10))

[False  True False]
[False  True  True]
[False  True False]


In [7]:
import numpy as np

c = np.array([[0, 1, 2], [3, 4, 5]])
print(c)

#행의 갯수
print(len(c))

#열의 갯수
print(len(c[0]))

d = np.array([
              [[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]],
              [[11,12,13,14],
               [15,16,17,18],
               [19,20,21,22]]
             ])
print(d)
print(len(d))
print(len(d[0]))
print(d.ndim)
print(d.shape)

[[0 1 2]
 [3 4 5]]
2
3
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]
2
3
3
(2, 3, 4)


In [10]:
import numpy as np

a=np.array([[0, 1, 2], [3, 4, 5]])
print(a[0, 0])
print(a[0, 1])
print(a[1, -1])

0
1
5


In [17]:
a=np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a
a[0, :]
a[:, 0:2]
a[1, 0:3]
a[:, 1]
a[1, 1:]

array([5, 6, 7])

In [37]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
print(m[1, 2])
print(m[2, 4])
print(m[1, 1:3])
print(m[1:, 2])
print(m[0:2, 3:5])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


In [41]:
import numpy as np

a=np.array([0,1,2,3,4,5,6,7,8,9])
idx=np.array([True, False, True, False, True
             , False, True, False, True, False])

print(a)
print(idx)
print(a[idx])

print(a%2)
print(a%2==0)
print(a[a%2==0])

[0 1 2 3 4 5 6 7 8 9]
[ True False  True False  True False  True False  True False]
[0 2 4 6 8]
[0 1 0 1 0 1 0 1 0 1]
[ True False  True False  True False  True False  True False]
[0 2 4 6 8]


In [44]:
a=np.array([11,22,33,44,55,66,77,88,99])
idx=np.array([0,2,4,6,8])
print(a[idx])

a=np.array([11,22,33,44,55,66,77,88,99])
idx=np.array([0,0,0,0,1,1,1,1,2,2,2,2])
print(a[idx])

[11 33 55 77 99]
[11 11 11 11 22 22 22 22 33 33 33 33]


In [45]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [46]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [47]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [48]:
a = np.zeros(5)
a.dtype

a

array([0., 0., 0., 0., 0.])

In [49]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
c = np.zeros((5, 2), dtype="i")
c

d = np.zeros(5, dtype="U4")
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d[3] = "가나다라마"
d

array(['abc', 'abcd', 'ABCD', '가나다라', ''], dtype='<U4')

In [57]:
b

f=np.ones_like(b, dtype="f")
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [58]:
g=np.empty((4, 3))
g

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323],
       [3.5e-323, 4.0e-323, 4.4e-323],
       [4.9e-323, 5.4e-323, 5.9e-323]])

In [61]:
np.linspace(0, 100, 11)
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])